### ISSUE TITLE
CTRL-F - Find shortcut?

### ISSUE THREAD

**Issue by MCS-Tech** [matt123p/TinyCAD#15]
Have used TinyCad since 2011. Still missing a shortcut for the "Find" function. 
CTRL-F is used in most other tools, and can not see that this is occupied?
Small issue, but would be very happy to see it implemented.

**Comment by ajshea** [comment]
Second this

**Comment by ajshea** [comment]
The latest release, 3.00.03, adds this shortcut to the "Edit" menu, but Ctrl-F does not actually function in my installation.

**Comment by beischer** [comment]
Same for me for 3.00.03. Just pressing 'f' opens the Find function (which is a great improvement), but Ctrl-F don't do this, even thought the menus says that it is now implemented.

**Comment by beischer** [comment]
Tried to find the bug, but my Win32 skills are not good enough. 

Can add the information that when a component is selected, Ctrl-F makes a flip

**Comment by matt123p** [comment]
OK.  I can't find the connection either.  It is definitely to do with the accelerator table but I can't figure out why it is still going wrong even when the accelerator table has been corrected.

I have however, fixed the problem, but simply switching the ID of "Find" and the ID of "Flip".  It now works!

**Comment by beischer** [comment]
What branch did you push to?

**Comment by beischer** [comment]
Found it in the develop branch. Thanks!
Have tested and it works for me too.
