### ISSUE TITLE
Copy Paste Funktion funktioniert nicht richtig für MS Word

### ISSUE THREAD

**Issue by Schaltplanfan** [matt123p/TinyCAD#24]
In der alten Version 2.90 konnte man alles mit "select all" auswählen, mit "Copy" in den Zwischenspeicher legen und nach dem Öffnen von MS Word darin einfügen. Das nun eingefügte Bild ist aber reduziert und nicht vollständig. Woran liegt das Problem?

**Comment by matt123p** [comment]
This should be fixed in 3.0.3, so I am closing.
