### ISSUE TITLE
Error With Printing and a suggestion

### ISSUE THREAD

**Issue by AshtonCAD** [matt123p/TinyCAD#31]
While using the circle shaped with white Fill. The printed paper shows a black filled circle instead.

Also is there a way to remove the title,author and date box. or have multiple templates. 
Thank You.

**Comment by matt123p** [comment]
1.  Can you upload the dsn file so I may check it? 
2. You can remove the display of the title, author etc., by going to File -> Design Details and unchecking the "Display Details" checkbox.

**Comment by ajshea** [comment]
Have you checked "print as black and white" in the print dialog? Checking this box results in all fills being printed black.

**Comment by AshtonCAD** [comment]
Sorry for not replying,
I fixed the fill white by not filling with color at all. The print still seems to be black though. The display details checkbox, that solved my problem.
Thank you for the response
