### ISSUE TITLE
Is it possible to cross-compile in Linux?

### ISSUE THREAD

**Issue by johnfound** [matt123p/TinyCAD#37]
I am using TinyCAD in Linux/WINE. 

Want to implement a lines grid instead of the dot grid.

Is it possible to cross-compile TinyCAD in Linux? I mean as a Windows PE executable, but using Linux tools.

I have tried to install VS on my work computer, but was not able to restore the NuGet packages, because of some security policies.

While my C++  programming skills should be enough for the above task, notice, that I am not competent in C/C++ programming and particularly in MS programming environment.

**Comment by matt123p** [comment]
I think you are going to struggle to use anything other than Visual Studio on Windows to compile TinyCAD.  I think you are going to have to get a Windows installation and do the work there.
