### ISSUE TITLE
Problems with inserted pictures

### ISSUE THREAD

**Issue by kayhko** [matt123p/TinyCAD#4]
Hi,
I have used v2.80.08 #631 to create schematics with inserted pictures in a separate sheet.

With v3.00.00r4  I can read the schematics sheets but not the sheet with the inserted picture.

Using a PC with Windows 10 Enterprise 64-bit

Se attached pictures

![TC3 00](https://user-images.githubusercontent.com/60179369/72892175-2c4c6380-3d16-11ea-859d-33bde6ca911e.JPG)
![TC2 80 08](https://user-images.githubusercontent.com/60179369/72892222-48500500-3d16-11ea-82b5-90f3e423bc16.JPG)

**Comment by matt123p** [comment]
Can I assume the picture was originally a JPEG file?  I have just fixed a bug around inserting JPEGs.

**Comment by kayhko** [comment]
Yes. copied from from the dsn file

		<IMAGE id='1' type='JPEG'>

**Comment by matt123p** [comment]
Please install the latest TinyCAD to get a fix for this issue.
