### ISSUE TITLE
TInyCad fails

### ISSUE THREAD

**Issue by StevenRudnick** [matt123p/TinyCAD#43]
When I tried to update TInyCad, both Windows and Norton objected and blocked the update. Then my tinycad file was locked so the program is now useless.
________________________________________

**Comment by matt123p** [comment]
If this is your personal PC then I suggest the following:

1. Download using Chrome rather than Edge.  It might complain but it will still let you download the file. 
2. Disable Norton before installing TinyCAD you can re-enable it after installing. 
3. If you get an error from Windows there should be an 'advanced' option or similar that will let you install it anyway.

If this is a work or school computer you will have to talk to your It department. 

Matt.

**Comment by StevenRudnick** [comment]
Category: Data Protector
Date & Time,Risk,Activity,Status,Recommended Action,Status,Program Path,Program Name,Date & Time,Action Observed,Target
10/5/2021 10:49:23 AM,High,Data Protector blocked a suspicious action by TinyCAD.exe,Action Blocked,No Action Required,Action Blocked,C:\Program Files (x86)\TinyCAD\TinyCAD.exe,TinyCAD.exe,10/5/2021 10:49:23 AM,Suspicious process attempted to lock a file protected by Data Protector,C:\Users\Steven\Documents\TinyCAD\library\74TTL.TCLib

And

***@***.***



And cannot open library - file is locked

**Comment by matt123p** [comment]
Please see here:
https://community.norton.com/en/forums/data-protector-stops-specific-program-constantly

Follow the instructions to exclude the folder C:\Users\Steven\Documents\TinyCAD\ from Norton data protector.

Matt.

**Comment by StevenRudnick** [comment]
I guessed at that earlier. Seems to work. Thanks.

Sent from my iPhone

On Oct 5, 2021, at 2:38 PM, matt123p ***@***.***> wrote:

﻿
EXTERNAL SENDER

Please see here:
https://community.norton.com/en/forums/data-protector-stops-specific-program-constantly<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcommunity.norton.com%2Fen%2Fforums%2Fdata-protector-stops-specific-program-constantly&data=04%7C01%7Csteven.rudnick%40umb.edu%7C26a8f1deeef14e21bf8108d9884022f3%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637690631326538179%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Yk1FyuKn5ygp%2FHpiz9ZW5DRjbaVA4s9tgBmqJYynQoc%3D&reserved=0>

Follow the instructions to exclude the folder C:\Users\Steven\Documents\TinyCAD\ from Norton data protector.

Matt.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmatt123p%2FTinyCAD%2Fissues%2F43%23issuecomment-934796032&data=04%7C01%7Csteven.rudnick%40umb.edu%7C26a8f1deeef14e21bf8108d9884022f3%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637690631326548128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ROrxcqB5AyCwYXcNMBHXsnFRPz5VGChertoOuVKjL5Q%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAV5JTFEIIWHISFCGPI4GE53UFNO5RANCNFSM5FKNIKQA&data=04%7C01%7Csteven.rudnick%40umb.edu%7C26a8f1deeef14e21bf8108d9884022f3%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637690631326548128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R8PNHVP%2Bd1ZS3GP2VYHecza641xGZ4jCvWMBLmCof%2Bw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csteven.rudnick%40umb.edu%7C26a8f1deeef14e21bf8108d9884022f3%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637690631326558083%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pmxsTHECjoVaZ6WDIgwJIqX5gWVt2e3KfYFWep7n%2F7s%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csteven.rudnick%40umb.edu%7C26a8f1deeef14e21bf8108d9884022f3%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637690631326558083%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=veKLaNdxkOHlmJhc42Umixap8k%2FRwTviJoVTye31YQ8%3D&reserved=0>.

**Comment by matt123p** [comment]
Good to hear.  I am glad you are up and running again.
