### ISSUE TITLE
Can I remove the file location in the design details?

### ISSUE THREAD

**Issue by thomas1999v** [matt123p/TinyCAD#58]
Can I remove the file location in the design details? (picture)
![Tinycad](https://user-images.githubusercontent.com/98651645/151664539-72631c53-d984-4c8d-918c-09839798d190.png)

**Comment by matt123p** [comment]
Hi,
Sorry no, this isn't possible at the moment.  However, you can remove this block altogether by going to the "Design Details" dialog under the file menu.  Un-tick the "display design details" check-box.

Thanks,
Matt.
