### ISSUE TITLE
Can't Delete Library Symbol

### ISSUE THREAD

**Issue by Cracklefish** [matt123p/TinyCAD#59]
Just upgraded to 3.00.04 and decided to tidy up my library but I find that I cannot delete any components. I get an error message:
"SQLITE_READONLY[8]: attempt to write to a readonly database"
Is this an installation issue, bug or finger trouble?
I'm running WIN 10 Pro x64 21H1

**Comment by matt123p** [comment]
It sounds like the library file is read-only.  Make sure the library file is under "My Documents" and check that the "read-only" flag is not set on it.

**Comment by Cracklefish** [comment]
Oops! Must have missed that bit, I'll move it Thanks for the help.
