### ISSUE TITLE
mfc140u.dll

### ISSUE THREAD

**Issue by The-Doc** [matt123p/TinyCAD#6]
I have the same problem as reported by Brutus11111 7 days ago.
The solution provided to Brutus does not work.
I have both the 32 bit and 64 bit C++ redistributables installed. See below.
Any thoughts??

![C++ Redistrib](https://user-images.githubusercontent.com/11254292/74031539-61dc8800-4977-11ea-83ac-f64ea5996483.jpg)

**Comment by matt123p** [comment]
It doesn't look like you have the redist for Visual Studio 2019, which is what was used to compile TinyCAD.

Can you try installing the latest 32 bit redist from here:
https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

**Comment by The-Doc** [comment]
Ah! I downloaded the 64 bit distribution yesterday by mistake.

 

Just downloaded the 32 bit, and TinyCad is now installed and has launched.

 

Thanks a lot Matt. 

 

Cheers

 

Peter Lapthorne

The DOC 35PC

Shoe Phone: +1 (907) 351-5569
