### ISSUE TITLE
Blatt Demension

### ISSUE THREAD

**Issue by Schaltplanfan** [matt123p/TinyCAD#7]
Die korrekten Blatt Maße werden im Set Page Size nicht dargestellt. Es steht immer fälschlicherweise 108 und 0 darin.
![2020-03-09 08_27_27-TinyCad -  tCad1](https://user-images.githubusercontent.com/61535534/76191543-dd805d80-61df-11ea-8025-e86ebf7444eb.png)

**Comment by matt123p** [comment]
1. Try clicking on "A4".
2. If that doesn't work, delete the registry entry for TinyCAD here:
      Computer\HKEY_CURRENT_USER\Software\TinyCAD\TinyCAD\1x20

**Comment by Schaltplanfan** [comment]
In der Version 2.90.00 konnte man bei der Blattgröße vier Stellen (9999mm) eingeben. Gerade bei A0 wird das gebraucht. Diese Hand Eingabe blieb dann auch gespeichert zur Seite. In 3.00.01 funktioniert das nicht mehr.
![2 90 00 Set Page Size](https://user-images.githubusercontent.com/61535534/76285241-9063c080-629f-11ea-9fc0-a33c3018c0d5.png)

**Comment by Schaltplanfan** [comment]
Bitte die Seite Größe wieder vierstellig einstellen.

**Comment by matt123p** [comment]
I have a fix for you.  Please email me at admin@tinycad.net and I will send you a link for a test installer.

**Comment by Schaltplanfan** [comment]
Thanks for the implementation.
